export const slugs = [
    "typescript",
    "javascript",
    "react",
    "html5",
    "css3",
    "nodedotjs",
    "express",
    "nextdotjs",
    "prisma",
    "mongodb",
    "php",
    "laravel",
    "tailwindcss",
    "python",
    "adobeillustrator",
    "thirdweb",
    "reactquery",
    "reacthookform",
    "recoil",
    "chartdotjs",
    "vite",
    "firebase",
    // "appwrite",
    "vercel",
    "jest",
    "git",
    "github",
    // "visualstudiocode",
    "figma",
    // "wordpress",
    // "clerk",
    //   "jira",
    //   "cypress",
    //   "docker",
    // "flask",
    //   "amazonaws",
    //   "postgresql",
    //   "nginx",
    // "testinglibrary",
    //   "gitlab",
    //   "androidstudio",
    //   "sonarqube",
  ];
  
export  const projects = [
    {
      id: 0,
      title: "Noteit",
      slug: "noteit",
      description: "Note app with AI Chatbot integration",
      img: "",
      link: "https://github.com/kryptcode/noteit",
      techs: ["Next.js", "Prisma", "Pinecone", "GPT"],
    },
    {
      id: 1,
      title: "xo Burgers",
      slug: "xo-burgers",
      description:
        "Website for a Burger-Focused Fast Food chain.",
      img: "https://i.ibb.co/SfycT3c/Screenshot-2024-07-13-at-10-55-22-Xo-Burgers.png",
      link: "https://xoburgers.vercel.app/",
      techs: ["Next.js", "TailwindCSS", "Framer Motion"],
    },
    {
      id: 2,
      title: "Disney+ ish",
      slug: "disneyish",
      description:
        "A clone of Disney's streaming platform's website. Shows and Movies are sourced from TMDb API. ",
      img: "https://i.ibb.co/XYCzcbn/Screenshot-2022-05-19-at-14-56-40-Disney.png",
      link: "http://disney-plus-psi.vercel.app/",
      techs: ["Next.js", "TailwindCSS", "TMDb API"],
    },
    {
      id: 3,
      title: "Audiophile",
      slug: "audiophile",
      description:
        "An online shopping application where you can shop for audio devices. It also provides features such as cart management multi-page routing etc.",
      img: "https://i.ibb.co/cXbLmBw/Screenshot-2023-12-13-at-21-07-57-Audiophile.png",
      link: "https://audio-phile-eight.vercel.app/",
      techs: ["Next.js", "TailwindCSS", "Context API"],
    },
    {
      id: 4,
      title: "Pan P",
      slug: "panp",
      description: "Multi-page website for pastry shop.",
      img: "https://i.ibb.co/m8tVb5y/Screenshot-2023-12-13-at-21-52-58-Pan-Buddies-Home.png",
      link: "https://pizza-boys.vercel.app/",
      techs: ["React", "TailwindCSS", "Vite"],
    },
    {
      id: 5,
      title: "Printico",
      slug: "printico",
      description: "Website for a small scale printing business.",
      img: "https://i.ibb.co/s6rKd0n/Screenshot-2022-07-30-at-11-32-04-Printico-Shop.png",
      link: "https://printico.vercel.app/",
      techs: ["Next.js", "TailwindCSS"],
    },
    {
      id: 6,
      title: "Kemi Portfolio",
      description: "Portfolio of a product manager and content writer.",
      img: "https://i.ibb.co/LhjjcJX/Screenshot-2023-12-29-at-09-22-11-Adekemi.png",
      link: "https://kemi-zeta.vercel.app",
      techs: ["Next.js", "TailwindCSS"],
    },
    {
      id: 7,
      title: "Gymate",
      description: "Multipage website for a gym.",
      img: "https://i.ibb.co/F76m2wq/Screenshot-2024-06-24-at-09-06-08-Gymate.png",
      link: "https://gymate-inky.vercel.app/",
      techs: ["React", "Vite", "TailwindCSS", "Recoil"],
    },
    {
      id: 8,
      title: "M.A.A.D. City Inks",
      techs: ["Next.js", "TailwindCSS", "aos"],
      description:
        "Multi-page website for a tattoo and piercing studio.",
      img: "https://i.ibb.co/FzS0nzY/Screenshot-2024-06-29-at-10-17-17-Maad-City-Tattoos.png",
      link: "https://maad-city.vercel.app",
    },
  ];
  
export  const content = [
    {
      id: 31,
      title: "QClose Inventory",
      description:
        "A feature-rich inventory website which combines cutting-edge inventory management, seamless point of sale integration, and convenient in-app chat functionality.",
      live: "https://qcloseinventory.com",
      img: "https://i.ibb.co/PGH3kt2/Screenshot-2023-12-13-at-21-08-57-QClose-Inventory.png",
      tools: [
        "https://www.svgrepo.com/show/493719/react-javascript-js-framework-facebook.svg",
        "https://www.svgrepo.com/show/374118/tailwind.svg",
        "https://www.svgrepo.com/show/353729/fastify-icon.svg",
      ],
    },
    {
      id: 32,
      title: "LinkStack",
      description: "Stack your links in one place. With page customization and bio.",
      live: "https://linkstack-ten-sigma.vercel.app",
      // github: "https://github.com/kryptcode/linkstack",
      img: "https://i.ibb.co/hBJC2dN/Screenshot-2024-06-21-at-10-39-47-Link-Stack.png",
      tools: ["Next.js", "TailwindCSS", "Express", "MongoDB", "Zustand"],
      techs: ["Next.js", "TailwindCSS", "Firebase", "Context API"],
    },
    {
      id: 33,
      title: "QClose Safety",
      description:
        "A safety application with incidents reporting, announcements, training and other features.",
      img: "https://i.ibb.co/BnwNvyN/Screenshot-2024-01-22-at-15-30-42-Dashboard-QClose-Safety.png",
      github: "",
      live: "https://qclosesafety.com/",
    },
    {
      id: 34,
      title: "MediVault EMR",
      description:
        " EMR for storing and managing patient data, ensuring robust, interoperable, and secure handling of healthcare information. ",
      img: "https://i.ibb.co/cDxz485/Screenshot-2024-07-05-at-20-39-17-Medi-Vault.png",
      github: "",
      live: "",
    },
    {
      id: 35,
      title: "Ọ̀rẹ́ Ọkàn",
      description:
      "A chatbot designed to address mental health issues and provide support in Yoruba.",
      img: "https://i.ibb.co/K5kYdqx/Screenshot-2024-06-15-at-20-44-04-Mental-Wellness-Bot.png",
      github: "https://github.com/kryptcode/mchl-yor-chatbot",
      techs: ["Next.js", "Flask", "Python", "Jupyter Notebook", "Clerk"],
    },
  ];

export const archives = [
    {
        id: 60,
        title: "My Team",
        slug: "myteam",
        description:
          "A responsive multipage website. Solution to Challenge by Frontend Mentor. ",
        img: "https://i.ibb.co/Bqjc2dw/Screenshot-2022-07-30-at-13-29-42-myteam-Home.png",
        link: "https://myteam-pi.vercel.app/",
        techs: ["Next.js", "TailwindCSS"],
      },
      {
        id: 61,
        title: "Steam Deck-ish",
        slug: "deckish",
        description: "Multi-page clone of the Steam Deck website.",
        img: "https://i.ibb.co/7VMnMGN/Screenshot-2023-12-13-at-21-15-28-Vite-React.png",
        link: "https://steam-deck.vercel.app/",
        techs: ["React", "TailwindCSS", "Vite"],
      },
      {
        id: 62,
        title: "RE Realtors",
        slug: "realtors",
        description: "Real Estate.",
        img: "https://i.ibb.co/LpPdrW1/Screenshot-2022-06-12-at-09-58-35-Real-Estate.png",
        link: "https://re-realtors.vercel.app/",
        techs: ["Next.js", "Chakra UI", "framer-motion"],
      },
      {
        id: 63,
        title: "Twitter ish",
        slug: "twittish",
        description:
          "Clone of social media app twitter with like, tweeting and commenting features added.",
        img: "https://i.ibb.co/stzt3pN/Screenshot-2022-06-13-at-21-29-31-Kami-Shiloh-on-Twitter-Who-am-I.png",
        link: "https://twitter-clone-z.vercel.app/",
        techs: ["Next.js", "TailwindCSS", "Firebase", "Recoil", "Next-Auth"],
      },
      {
        id: 64,
        title: "OpenSea Sembuild",
        slug: "opensea",
        description: "Built on Rinkeby testnet. Website built for buying NFTs.",
        img: "https://i.ibb.co/stzt3pN/Screenshot-2022-06-13-at-21-29-31-Kami-Shiloh-on-Twitter-Who-am-I.png",
        link: "http://nmkt.vercel.app/",
        techs: ["Next.js", "TailwindCSS", "ThirdWeb"],
      },
      {
        id: 65,
        title: "AirBnB ish",
        slug: "airbnb",
        description: "AirBnB clone",
        img: "https://i.ibb.co/Kq7DfT2/Screenshot-2022-05-19-at-15-11-03-Airbnb-Clone.png",
        link: "https://airbnb-clone-zeta-nine.vercel.app/",
        techs: ["Next.js", "React-Map-GL", "GeoLib"],
      },
      {
        id: 66,
        title: "Hulu ish",
        description: "Hulu home page built with nextjs and tmdb api.",
        img: "https://i.ibb.co/8Yd3TM9/Screenshot-2023-12-13-at-21-13-53-Hulu-Clone.png",
        link: "http://hulu-clone-rose-nine.vercel.app/",
        techs: ["Next.js", "TMDb", "TailwindCSS"],
      },
      {
        id: 67,
        title: "CarHub",
        description: "Car rentals website.",
        img: "https://i.ibb.co/3B63rym/Screenshot-2024-06-24-at-09-01-10-Car-Hub.png",
        link: "https://carhub-sage.vercel.app/",
        techs: ["Next.js", "TypeScript", "TailwindCSS"],
      },
      {
        id: 68,
        title: "c-rentals",
        description: "Car rentals website.",
        img: "https://i.ibb.co/YhRRbD1/Screenshot-2024-06-24-at-09-02-48-CRentals.png",
        link: "https://c-rentals.vercel.app/",
        techs: ["React", "Vite", "recoil", "aos"],
      },
]